name: requirements_j
channels:
  - conda-forge

dependencies:
  - python=3.11
  - streamlit
  - pandas
  - geopandas
  - matplotlib
  - requests
  - pytest
  - pillow
  - pyyaml
  - pip
  - pip:
      - ollama
      - protobuf==3.20.3