name: requirements_j
channels:
  - conda-forge

dependencies:
  - python=3.11
  - streamlit>=1.30
  - altair>=5
  - pandas
  - geopandas
  - shapely
  - matplotlib
  - requests
  - pytest
  - pillow
  - pyyaml
  - pydantic
  - pip
  - pip:
      - ollama